export const ActionTypes = {
  CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
  GET_TODO_REQUEST: 'GET_TODO_REQUEST',
  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  COMPLETE_TODO_REQUEST: 'COMPLETE_TODO_REQUEST',
};
